<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-8IGUF9C" ignored="0" name="Casos de Pruebas Nuevos" tests="4" failures="1" timestamp="2021-09-06T17:05:52 COT" time="0.023" errors="0">
  <testcase name="tercerSetPruebaCuatro" time="0.001" classname="anotacionestestng.TercerSet">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at anotacionestestng.TercerSet.tercerSetPruebaCuatro(TercerSet.java:22)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- tercerSetPruebaCuatro -->
  <testcase name="tercerSetPruebaDos" time="0.002" classname="anotacionestestng.TercerSet"/>
  <testcase name="tercerSetPruebaTres" time="0.001" classname="anotacionestestng.TercerSet"/>
  <testcase name="tercerSetPruebaUno" time="0.002" classname="anotacionestestng.TercerSet"/>
</testsuite> <!-- Casos de Pruebas Nuevos -->
